spring.application.name=FacturacionElectronicaJava

spring.datasource.url=jdbc:postgresql://207.58.175.220:5432/facturacion
spring.datasource.username=samuelnasa375
spring.datasource.password=samuelnasa3752026
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de JPA/Hibernate (opcional para desarrollo)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080